name: Setup

runs:
  using: "composite"
  steps:
    - name: Cache /var/lib/apt
      uses: actions/cache@v4
      with:
        path: /var/lib/apt
        key: ${{ runner.os }}-var-lib-apt
    - name: Cache /var/cache/apt
      uses: actions/cache@v4
      with:
        path: /var/cache/apt
        key: ${{ runner.os }}-var-cache-apt
    - name: check /etc/apt/apt.conf.d/
      run: |
        ls -al /etc/apt/apt.conf.d/
      shell: bash
    - name: setup git-restore-mtime
      run: |
        sudo apt-get install -y git-restore-mtime
      shell: bash
    - name: setup blogsync
      uses: x-motemen/blogsync@9760a4c471a07ca7d471dd9f09ecbb258f6da6b0 # v0.20.1
      with:
        version: v0.20.1
    - name: restore mtime
      run: |
        git restore-mtime
      shell: bash
